### ISSUE TITLE
no thermal_proc.launch error

### ISSUE THREAD

**Issue by ak2792797** [tu-darmstadt-ros-pkg/hector_tracker_install#1]
roslaunch hector_tracker_sim_launch spawn_tracker_with_ground_truth.launch 
stdout:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/shrek/catkin_hector_tracker/hector_tracker_install/src/hector_vehicle_launch/hector_onboard_launch/launch/thermal_proc.launch'
The traceback for the exception was written to the log file

**Comment by skohlbr** [comment]
Arg, forgot that in commit, but have it on another machine. Will be fixed later today (~7h).

**Comment by skohlbr** [comment]
Fixed temporarily by adding empty launch file: https://github.com/tu-darmstadt-ros-pkg/hector_vehicle_launch/commit/f61adbbfaef494600734b84daa54c2c78a870b6f

**Comment by skohlbr** [comment]
Fixed now, using proper launch file.
